//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from f:/fisiere/C#/Tema 2 LFC/Tema 2 LFC - Copie/Tema 2 LFC/MiniLanguage.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MiniLanguageParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMiniLanguageVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] MiniLanguageParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] MiniLanguageParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] MiniLanguageParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assign</c>
	/// labeled alternative in <see cref="MiniLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] MiniLanguageParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>plusAssign</c>
	/// labeled alternative in <see cref="MiniLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlusAssign([NotNull] MiniLanguageParser.PlusAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>minusAssign</c>
	/// labeled alternative in <see cref="MiniLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMinusAssign([NotNull] MiniLanguageParser.MinusAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multiplyAssign</c>
	/// labeled alternative in <see cref="MiniLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplyAssign([NotNull] MiniLanguageParser.MultiplyAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>divideAssign</c>
	/// labeled alternative in <see cref="MiniLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivideAssign([NotNull] MiniLanguageParser.DivideAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>moduloAssign</c>
	/// labeled alternative in <see cref="MiniLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuloAssign([NotNull] MiniLanguageParser.ModuloAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assignExpression</c>
	/// labeled alternative in <see cref="MiniLanguageParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignExpression([NotNull] MiniLanguageParser.AssignExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.logicalOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOr([NotNull] MiniLanguageParser.LogicalOrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.logicalAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAnd([NotNull] MiniLanguageParser.LogicalAndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.equality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquality([NotNull] MiniLanguageParser.EqualityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.relational"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational([NotNull] MiniLanguageParser.RelationalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.additive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditive([NotNull] MiniLanguageParser.AdditiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.multiplicative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicative([NotNull] MiniLanguageParser.MultiplicativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary([NotNull] MiniLanguageParser.UnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.postfix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix([NotNull] MiniLanguageParser.PostfixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] MiniLanguageParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] MiniLanguageParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] MiniLanguageParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] MiniLanguageParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatement([NotNull] MiniLanguageParser.BlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] MiniLanguageParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.forInitialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInitialization([NotNull] MiniLanguageParser.ForInitializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] MiniLanguageParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] MiniLanguageParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] MiniLanguageParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] MiniLanguageParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] MiniLanguageParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] MiniLanguageParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.parametersList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametersList([NotNull] MiniLanguageParser.ParametersListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniLanguageParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] MiniLanguageParser.FunctionDeclarationContext context);
}
